-- truncate tb_ruta_mb;
SELECT 
distinct
H_COD_CLIENTE
,H_RUTA
,H_USUARIO  
,h_fecha
FROM TB_HISTORIAL_MB
WHERE 1=1
AND DATE(H_FECHA) >='2017-06-01'
    AND DATE(H_FECHA) <DATE_ADD('2017-06-01',INTERVAL 1 DAY)
    AND H_COD_CLIENTE <>'null'
    AND H_USUARIO='QU19'
ORDER BY H_FECHA ASC;
	
SELECT * FROM TB_RUTA_MB;
            
SELECT 
		A.H_COD_CLIENTE AS CLIENTE_VISITADO
		,B.R_RUTA
        ,A.H_ACCION
        ,A.H_FECHA
        ,DAYOFWEEK(A.H_FECHA)
	FROM TB_HISTORIAL_MB AS A
	INNER JOIN TB_RUTA_MB AS B
		ON A.H_COD_CLIENTE=B.R_COD_CLIENTE
	WHERE 1=1  
		AND A.H_FECHA>='2017-06-01 00:00:00'
        AND A.H_FECHA<='2017-06-01 23:59:59'
		AND A.H_ACCION='Inicio visita'
        AND A.H_COD_USUARIO='QU19'
		AND A.H_COD_CLIENTE IS NOT NULL
ORDER BY A.H_USUARIO, A.H_FECHA ASC;

SELECT R_COD_CLIENTE, R_SECUENCIA
FROM TB_RUTA_MB
WHERE 1=1
	AND R_DIA=5
    AND R_ESTATUS=1
	AND RIGHT(R_RUTA,3)='LOJ';