SELECT DISTINCT RIGHT(R_RUTA,3), LENGTH(RIGHT(R_RUTA,3)) FROM TB_RUTA_MB;
SELECT 
			R_RUTA
			, R_SECUENCIA 
		FROM TB_RUTA_MB 
        WHERE 1=1
			-- AND R_COD_CLIENTE=COD_CLIENTE
			AND RIGHT(R_RUTA,3)='LOJ';
    

SELECT * FROM tb_control_ruta;
SELECT COUNT(*) FROM tb_control_ruta;
TRUNCATE tb_control_ruta; 

call revisionRuta ('2017-06-01','LOJ','QU20',5,1);
SHOW WARNINGS;
-- QU19
SET @FECHA_VISITA='2017-06-01';
SET @INICIAL_EJE='LOJ';
SET @COD_EJE='QU19';
SELECT 
	H_COD_CLIENTE,H_RUTA,H_USUARIO
FROM TB_HISTORIAL_MB 
WHERE 1=1
	AND DATE(H_FECHA) >=@FECHA_VISITA 
    AND DATE(H_FECHA) <DATE_ADD(@FECHA_VISITA,INTERVAL 1 DAY)
	AND H_COD_CLIENTE !='null'
	AND H_USUARIO='QU19'
	AND H_RUTA !='null'
	AND H_ACCION ='Inicio visita';

SET @FECHA_VISITA='2017-06-01';    
SELECT DATE_ADD(DATE(@FECHA_VISITA),INTERVAL 1 DAY) AS A;

-- Error Code: 1329. No data - zero rows fetched, selected, or processed


SELECT DATE_ADD(DATE('2017-06-01'),INTERVAL 1 DAY) AS A;


SET @FECHA_VISITA='2017-06-01';
SELECT DISTINCT
	H_COD_CLIENTE,H_RUTA,H_USUARIO,H_ACCION,H_FECHA
FROM TB_HISTORIAL_MB 
WHERE 1=1
	AND DATE(H_FECHA) >=@FECHA_VISITA 
    AND DATE(H_FECHA) <DATE_ADD(@FECHA_VISITA,INTERVAL 1 DAY)
    AND H_COD_CLIENTE !='null'
    AND H_USUARIO='QU19'
    AND H_ACCION ='Inicio visita'
ORDER BY H_FECHA ASC;

SET @RUTA_EJECUTIVO='HOLA';
SET @SECUENCIA_RUTA_EJECUTIVO='HOLA 1';
SELECT 
			R_RUTA
			, R_SECUENCIA 
            INTO 
            @RUTA_EJECUTIVO
            ,@SECUENCIA_RUTA_EJECUTIVO
		FROM TB_RUTA_MB 
        WHERE 1=1
			-- AND R_COD_CLIENTE=COD_CLIENTE
			AND RIGHT(R_RUTA,3)='LOJ';
SELECT @RUTA_EJECUTIVO, @SECUENCIA_RUTA_EJECUTIVO;
